import React from 'react';
import { FinancialAnalysis, Recommendation } from '../types';
import RatioCard from './RatioCard';
import DataChart from './DataChart';

interface ReportForPDFProps {
  result: FinancialAnalysis;
}

const getRecommendationPDFClasses = (recommendation: Recommendation) => {
  switch (recommendation) {
    case 'Buy':
      return 'bg-green-100 border-green-300 text-green-800';
    case 'Hold':
      return 'bg-yellow-100 border-yellow-300 text-yellow-800';
    case 'Sell':
      return 'bg-red-100 border-red-300 text-red-800';
    default:
      return 'bg-gray-100 border-gray-300 text-gray-800';
  }
};


const ReportForPDF: React.FC<ReportForPDFProps> = ({ result }) => {
  const A4_WIDTH_PX = 794; 

  return (
    <div style={{ width: `${A4_WIDTH_PX}px` }} className="bg-white text-gray-900 font-sans p-10">
      <header className="text-center mb-8 border-b-2 border-gray-300 pb-4">
        <h1 className="text-4xl font-bold text-gray-800">Financial Analysis Report</h1>
        <p className="text-lg text-gray-600">Generated by AI Financial Statement Analyzer</p>
      </header>

      <main className="space-y-8">
        {/* Header Section */}
        <section className="bg-gray-50 p-6 rounded-lg border border-gray-200 flex justify-between items-center">
          <div>
            <p className="text-sm text-gray-500">Company</p>
            <h2 className="text-2xl font-bold text-blue-800">{result.companyName}</h2>
            <p className="text-blue-700 font-semibold text-lg">{result.statementType}</p>
          </div>
          <div className="text-center">
            <p className="text-gray-600 text-sm mb-1 font-semibold">Investment Recommendation</p>
            <span className={`px-6 py-2 text-xl font-bold rounded-full shadow-sm border ${getRecommendationPDFClasses(result.recommendation)}`}>
              {result.recommendation}
            </span>
          </div>
        </section>

        {/* CFA Summary Section */}
        <section>
          <h3 className="text-2xl font-semibold mb-4 text-gray-800 border-b pb-2">Analyst Summary</h3>
          <div className="space-y-4 text-gray-700 p-4 bg-gray-50 rounded-lg">
              <div>
                  <h4 className="font-semibold text-green-700 text-lg">Strengths</h4>
                  <p>{result.summary.strengths}</p>
              </div>
              <div className="mt-4">
                  <h4 className="font-semibold text-red-700 text-lg">Weaknesses</h4>
                  <p>{result.summary.weaknesses}</p>
              </div>
              <div className="mt-4">
                  <h4 className="font-semibold text-yellow-700 text-lg">Outlook</h4>
                  <p>{result.summary.outlook}</p>
              </div>
          </div>
        </section>
        
        {/* Ratios Section */}
        <section>
          <h3 className="text-2xl font-semibold mb-4 text-gray-800 border-b pb-2">Key Financial Ratios</h3>
          <div className="grid grid-cols-2 gap-4">
            {result.ratios.map((ratio, index) => (
              <RatioCard key={index} ratio={ratio} theme="light" />
            ))}
          </div>
        </section>

        {/* Data & Visuals Section */}
        <section>
           <h3 className="text-2xl font-semibold mb-4 text-gray-800 border-b pb-2">Data & Visual Insights</h3>
            <div className="grid grid-cols-5 gap-6">
                <div className="col-span-2 bg-gray-50 p-4 rounded-lg border border-gray-200">
                    <h4 className="text-xl font-semibold mb-3 text-gray-700">Extracted Data</h4>
                    <div className="max-h-96 overflow-y-auto">
                        <table className="w-full text-left text-sm">
                            <thead>
                                <tr>
                                    <th className="p-2 font-semibold text-blue-800 border-b-2 border-gray-300">Metric</th>
                                    <th className="p-2 font-semibold text-blue-800 border-b-2 border-gray-300 text-right">Value</th>
                                </tr>
                            </thead>
                            <tbody>
                            {result.extractedData.map((data, index) => (
                                <tr key={index} className="border-b border-gray-200 last:border-b-0">
                                <td className="p-2 text-gray-700">{data.metric}</td>
                                <td className="p-2 font-mono text-gray-800 text-right">{data.value}</td>
                                </tr>
                            ))}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div className="col-span-3 bg-gray-50 p-4 rounded-lg border border-gray-200 flex flex-col items-center justify-center">
                    <h4 className="text-xl font-semibold mb-3 text-gray-700">Visual Insights</h4>
                    <DataChart data={result.extractedData} theme="light" />
                </div>
            </div>
        </section>
      </main>

      {/* Disclaimer */}
      <footer className="mt-10 pt-4 border-t border-gray-300 text-center">
          <h4 className="font-semibold text-gray-600 mb-2">Disclaimer</h4>
          <p className="text-xs text-gray-500">{result.cfaDisclaimer}</p>
      </footer>
    </div>
  );
};

export default ReportForPDF;